# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 10 Jul 2018 08:38:57 +0000
*	@ALL	1
*	@user	1
diario:*	@ALL	1
diario:*	@alldiario	1
tecno:*	@ALL	1
