<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: joevr
 * Date: Mon, 31 Jul 2023 16:35:34 +0200
 */

$conf['title'] = 'Joe\'s Experienced Docs';
$conf['lang'] = 'it';
$conf['template'] = 'ad-hominem';
$conf['license'] = '0';
$conf['dformat'] = '%d/%m/%Y %H:%M';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
