<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: joevr
 * Date: Thu, 03 Aug 2023 11:53:47 +0200
 */

$conf['title'] = 'Joe\'s Experienced Docs';
$conf['lang'] = 'it';
$conf['template'] = 'ad-hominem';
$conf['license'] = '0';
$conf['dformat'] = '%d/%m/%Y %H:%M';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['goto']['seconds'] = 0;
$conf['plugin']['goto']['minSeconds'] = 0;
